name: MoreCommands
author: CrazedMiner
version: [3.0.0-ALPHA11]
description: Simple Plugin that Adds More Commands to your PocketMine Server!
main: \MoreCommands\Main
api: 1.12.0

commands:
    spawn:
        description: "Teleports you to Spawn"
    hub:
        description: "Teleports you to the Hub"
    lobby:
        description: "Teleports you to the Lobby"
